const state={slides:[],index:0,paused:false,run:0,timer:null,audio:null,audioOn:false,completed:new Set()};
const $=(selector,root=document)=>root.querySelector(selector);
const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
const printSelectors='.hero-note,.lesson .intro-card p,.lesson .quote-line strong,.lesson .section-lead,.lesson .principles h3,.lesson .principles p,.lesson .compare-head span,.lesson .compare-row p,.lesson .language-grid h3,.lesson .language-grid p,.lesson .purpose-list button span,.lesson .genre-grid strong,.lesson .genre-grid p,.lesson .structure-track h3,.lesson .structure-track p,.lesson .rewrite span,.lesson .rewrite p,.lesson .caption,.lesson .check-list label,.lesson .final-copy';
function textNodes(element){const walker=document.createTreeWalker(element,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())if(walker.currentNode.nodeValue.trim())nodes.push(walker.currentNode);return nodes}
function delay(ms,run){return new Promise(resolve=>{let left=ms,last=performance.now();function step(now){if(run!==state.run)return resolve(false);if(!state.paused&&!document.body.classList.contains('sheet-open'))left-=now-last;last=now;if(left<=0)return resolve(true);requestAnimationFrame(step)}requestAnimationFrame(step)})}
async function typeElement(element,run){const chars=element._typedChars||[];if(!chars.length)return true;element.classList.add('is-typing');for(const char of chars){if(run!==state.run)return false;while(state.paused){await new Promise(resolve=>setTimeout(resolve,100));if(run!==state.run)return false}char.classList.add('shown');await delay(char.textContent===' '?5:11,run);if(run!==state.run)return false}element.classList.remove('is-typing');element.classList.add('is-typed');return true}
async function playSlide(index){if(index<0||index>=state.slides.length)return;state.run++;const run=state.run;state.index=index;const slide=state.slides[index];const alreadyPlayed=state.completed.has(index);state.slides.forEach((item,i)=>{item.classList.toggle('is-active',i===index);item.setAttribute('aria-hidden',String(i!==index))});
  $('#progressFill').style.transform=`scaleX(${(index+1)/state.slides.length})`;
  $$('.nav-button').forEach(button=>{const step=Number(button.dataset.step);button.disabled=(step<0&&index===0)||(step>0&&index===state.slides.length-1)});
  const targets=$$(printSelectors,slide);
  if(!alreadyPlayed){targets.forEach(target=>{if(target._sourceHTML===undefined)target._sourceHTML=target.innerHTML;const checked=target.matches('.check-list label')?$('input',target)?.checked:null;target.innerHTML=target._sourceHTML;target.classList.remove('is-typed','is-typing');const accessibleText=target.textContent;for(const node of textNodes(target)){const runNode=document.createElement('span');runNode.className='typed-run';for(const character of node.nodeValue){const span=document.createElement('span');span.className='typed-char';span.setAttribute('aria-hidden','true');span.textContent=character;runNode.append(span)}node.replaceWith(runNode)}const accessibleCopy=document.createElement('span');accessibleCopy.className='sr-only';accessibleCopy.textContent=accessibleText;target.append(accessibleCopy);if(target.matches('.check-list label')){const input=$('input',target);if(input){input.checked=checked;input.setAttribute('aria-label',accessibleText)}}target._typedChars=$$('.typed-char',target)});const title=$('h1, h2',slide);if(title)title.classList.remove('title-seen');requestAnimationFrame(()=>title?.classList.add('title-seen'))}else{slide.classList.add('has-played');targets.forEach(target=>{target._typedChars?.forEach(char=>char.classList.add('shown'));target.classList.add('is-typed')})}
  const progress=$('.slide-progress');progress?.setAttribute('aria-valuenow',String(index+1));progress?.setAttribute('aria-valuemax',String(state.slides.length));
  if(alreadyPlayed){if(run===state.run&&index!==state.slides.length-1)await delay(2000,run);if(run===state.run&&index!==state.slides.length-1)playSlide(index+1);return}
  if(reducedMotion){for(const target of targets){target._typedChars.forEach(char=>char.classList.add('shown'));target.classList.add('is-typed')}state.completed.add(index);slide.classList.add('has-played');await delay(4500,run);if(run===state.run)playSlide((index+1)%state.slides.length);return}
  await delay(850,run);for(const target of targets){if(run!==state.run)return;const ok=await typeElement(target,run);if(!ok)return}
  if(run!==state.run)return;state.completed.add(index);slide.classList.add('has-played');if(index===state.slides.length-1)return;await delay(2000,run);if(run===state.run)playSlide(index+1)
}
function go(delta){playSlide(Math.max(0,Math.min(state.slides.length-1,state.index+delta)))}

state.slides=[$('.hero'),...$$('.lesson')].filter(Boolean);
state.slides.forEach((slide,index)=>{slide.dataset.slide=index;slide.setAttribute('role','group');slide.setAttribute('aria-roledescription','слайд')});
$$('.nav-button').forEach(button=>button.addEventListener('click',()=>go(Number(button.dataset.step))));
const ambientVideo=$('.ambient-video');ambientVideo?.addEventListener('error',()=>$('.ambient-bg')?.classList.add('video-error'));ambientVideo?.addEventListener('loadeddata',()=>$('.ambient-bg')?.classList.remove('video-error'));if(reducedMotion)ambientVideo?.pause();
const pauseIcon='<svg class="button-icon icon-pause" viewBox="0 0 24 24" aria-hidden="true"><path d="M8 5v14M16 5v14"/></svg>',playIcon='<svg class="button-icon icon-play" viewBox="0 0 24 24" aria-hidden="true"><path d="m9 6 9 6-9 6V6Z"/></svg>',soundOnIcon='<svg class="button-icon icon-sound" viewBox="0 0 24 24" aria-hidden="true"><path d="M5 10v4h3l4 3V7L8 10H5Z"/><path class="sound-wave" d="M16 9.5a4 4 0 0 1 0 5M18.5 7a7.5 7.5 0 0 1 0 10"/></svg>',soundOffIcon='<svg class="button-icon icon-sound-off" viewBox="0 0 24 24" aria-hidden="true"><path d="M5 10v4h3l4 3V7L8 10H5Z"/><path d="m16 9 5 6m0-6-5 6"/></svg>';
$('#pauseButton').addEventListener('click',event=>{state.paused=!state.paused;event.currentTarget.innerHTML=state.paused?playIcon:pauseIcon;event.currentTarget.setAttribute('aria-label',state.paused?'Жалғастыру':'Анимацияны кідірту');event.currentTarget.setAttribute('aria-pressed',String(state.paused));document.body.classList.toggle('is-paused',state.paused);if(state.paused){ambientVideo?.pause();if(state.audioOn)state.audio?.pause()}else{if(!reducedMotion)ambientVideo?.play().catch(()=>{});if(state.audioOn)state.audio?.play().catch(()=>{})}});
document.addEventListener('keydown',event=>{if(document.body.classList.contains('sheet-open')){if(event.key==='Escape')closeSheet();return}if(['ArrowRight','ArrowDown','PageDown',' '].includes(event.key)){event.preventDefault();go(1)}else if(['ArrowLeft','ArrowUp','PageUp'].includes(event.key)){event.preventDefault();go(-1)}else if(event.key.toLowerCase()==='p')$('#pauseButton').click()});
let wheelLock=false;document.addEventListener('wheel',event=>{if(wheelLock||document.body.classList.contains('sheet-open'))return;if(event.target.closest('.lesson, .comparison-scroll'))return;if(Math.abs(event.deltaY)<28)return;wheelLock=true;go(event.deltaY>0?1:-1);setTimeout(()=>wheelLock=false,850)},{passive:true});
let touchStart=0;document.addEventListener('touchstart',event=>{touchStart=event.touches[0]?.clientY||0},{passive:true});document.addEventListener('touchend',event=>{const delta=touchStart-(event.changedTouches[0]?.clientY||touchStart);if(Math.abs(delta)>60)go(delta>0?1:-1);touchStart=0},{passive:true});

function closeSheet(){document.body.classList.remove('sheet-open');$('#sheet').setAttribute('aria-hidden','true')}
function openSheet(button){$('#sheetTitle').textContent=button.dataset.goal;$('#sheetCopy').textContent=button.dataset.copy;document.body.classList.add('sheet-open');$('#sheet').setAttribute('aria-hidden','false');$('#sheetClose').focus()}
$$('.purpose-list button').forEach(button=>button.addEventListener('click',()=>openSheet(button)));$('#sheetClose').addEventListener('click',closeSheet);$('#sheetBackdrop').addEventListener('click',closeSheet);
function initAudio(){state.audio=$('#ambientAudio');if(state.audio){state.audio.volume=.08;state.audio.loop=true}}
$('#soundButton').addEventListener('click',async event=>{if(!state.audio)initAudio();if(!state.audio)return;state.audioOn=!state.audioOn;if(state.audioOn)await state.audio.play().catch(()=>{});else state.audio.pause();event.currentTarget.innerHTML=state.audioOn?soundOffIcon:soundOnIcon;event.currentTarget.setAttribute('aria-label',state.audioOn?'Дыбысты өшіру':'Дыбысты қосу');event.currentTarget.setAttribute('aria-pressed',String(state.audioOn))});
if(matchMedia('(pointer:fine)').matches)document.addEventListener('pointermove',event=>{document.documentElement.style.setProperty('--slide-x',`${(event.clientX/innerWidth-.5)*14}px`);document.documentElement.style.setProperty('--slide-y',`${(event.clientY/innerHeight-.5)*14}px`)});
playSlide(0);
